# POST http://localhost:3000/v1/api/register
# Content-Type: application/json

# {
#   "name": "Aice",
#   "email": "adaadsdasdasom",
#   "password": "13456"
# }

POST http://localhost:3000/v1/api/login
Content-Type: application/json

{
  "email": "adaadsdasdasom",
  "password": "13dsadas456"
}